/**:
  ros__parameters:
    output_topic: /perception/occupancy_grid_map/map
    frame_id: map
    resolution: 0.5
    width_m: 400.0
    height_m: 400.0
    center_x: 0.0
    center_y: 0.0
    auto_center_from_odometry: true
    odometry_topic: /localization/kinematic_state
    publish_rate_hz: 1.0
